### ISSUE TITLE
Decide on default port of integrations-registry service

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations-registry#11]
The current default port is `8080`. We should discuss what the default port for it should be. 

As the integrations registry will run as a HTTP based service my suggestion would be `80` / `443`.

**Comment by ruflin** [comment]
@jfsiii @jasonrhodes would be great to get your feedback on this one.

**Comment by jfsiii** [comment]
SGTM. I don't think the Integrations Manager has an opinion. From its POV, the registry location is an origin string with a domain and optional host which can be practically anything. It defaults to the registry's default location, but the user can set to `http://localhost`, `https://registry.example.local:1337`, etc

**Comment by ruflin** [comment]
Thanks to https://github.com/elastic/integrations-registry/pull/12 the port and address are now configurable. As it is an http endpoint, I suggest we stick to 8080 as default.
