### ISSUE TITLE
Add title property to list & package responses

### ISSUE THREAD

**Issue by jfsiii** [elastic/integrations-registry#43]
While working on the list and detail views for the Integrations Manager, it became apparent we need to support a stylized version of the integration name, e.g. "Apache" or "PostgreSQL".

I think "title" works but happy to iterate on a better name.

**Comment by jfsiii** [comment]
One alternative to adding a field is to repurpose the `name` field. 

It's currently, as I understand, all lower case and (in combination with version) used as a key for the packages.

If the Registry response had a mixed-case `name`, the Manager could transform it to lowercase before requesting a package or the Registry could ignore case for requests.

**Comment by ruflin** [comment]
+1 on using title as I predict the automatic way will break earlier or later when we have spaces or other things in the names. We had such auto magic in the past for our modules docs and it didn't go well.
