### ISSUE TITLE
Discuss icon response restrictions

### ISSUE THREAD

**Issue by jfsiii** [elastic/integrations-registry#45]
## Current
`icon` is a string which returns a relative path to an image (or possibly any asset type?)

## Challenges include
1. No guidance or consistency on image dimensions, format, resolution (portrait, 32x32, image-name@2x, etc)
1. Missing support for the Elastic and Third Party logos from [`EuiIcon`](https://elastic.github.io/eui/#/display/icons) which are the majority of the initial integrations.
1. Issues using `<img>` tags with [`EuiCard`](https://elastic.github.io/eui/#/display/card) (can't use with Horizontal Layouts, essentially forces a single layout/appearance, etc).

## Options include
1. Maintaining status quo
1. Convert `icon` to values compatible with `EuiIcon` (e.g. enum of icon names, string URL to SVG, or string of inline SVG)
1. Add a separate entry or otherwise make a distinction between raster images and SVG (e.g. `iconUrl` & `iconType`)

**Comment by jfsiii** [comment]
I don't think Option 1 is really a viable choice.

Whether we go for 2, 3 or another one, I think we should prioritize (if not exclusively support) SVG. They are quite common and eliminate several categories of challenges with raster images. 

I also think it's consistent with our progressive/iterative approach to support the needs/resources we have now (svg asset icons) and think about other cases later.

**Comment by ruflin** [comment]
+1 on having SVG images as it will eliminate the scale discussion (I hope). Are there downsides of only supporting SVGs?

**Comment by jfsiii** [comment]
The first one which occurs to me is that not every project has an SVG asset. This is more true when we eventually open up to outside contributions.

**Comment by jfsiii** [comment]
We could follow the example from the [Web App Manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest) have an [`icons`](https://developer.mozilla.org/en-US/docs/Web/Manifest/icons) section which looks like:

```
"icons": [
  {
    "src": "/img/icon.svg",
    "sizes": "16x16 32x32 96x96 128x128 256x256"
   },
  {
    "src": "/img/icon-192.png",
    "type": "image/png",
    "sizes": "192x192"
  },
  {
    "src": "/img/icon-512.png",
    "type": "image/png",
    "sizes": "512x512"
  }
]
```

The `src` values don't matter here, they're just the path to the asset. `type` and `sizes` give the information about it.

`type` and `sizes` could be optional with common defaults. We could limit the types we support or leave it open. Similar thing with `sizes`. e.g. require it work at 32px and 128px, suggest increments of X px, etc

**Comment by ruflin** [comment]
Could we also just go with:

```
"icons": [
  {
    "src": "/img/icon.svg",
   },
  {
    "src": "/img/icon-192.png",
  },
  {
    "src": "/img/icon-512.png",
  }
]
```

Or will you need the additional information for querying in some way on the consumer side?

Based on both outputs above, our convention would be:

* Images must be square
* If not svg, they must contain the size in the icon name.

The part I missed is on why the svg also contains sizes as it "should" look good in any size?

**Comment by jfsiii** [comment]
Why use an object if it has only one key? At that point, it might as well go to 

```
"icons": [
  "/img/icon.svg",
  "/img/icon-192.png",
  "/img/icon-512.png",
]
```

That said, I'd really like to avoid this.

> If not svg, they must contain the size in the icon name.

I think labeling the individual pieces is preferable to creating a DSL inside a string.

Using the "size in the filename" approach means pushing logic ("check the extension, if some test, split/parse the string, grab the size") to the edge/consumer when we could label it once here.

> Images must be square

Seems reasonable

> If not svg, they must contain the size in the icon name.

See comments above

>  why the svg also contains sizes as it "should" look good in any size?

See: "`sizes` could be optional". That said, while SVG's do scale without the blurring you get with raster images, there's the possibility that the author would like make different icons for different sizes. A 16 or 32 px wide icon is visually very different from a 192 or 256 one. They might cut elements out that are distracting or imperceptible at small sizes. Or take advantage of the extra space at large sizes.

**Comment by ruflin** [comment]
Using an object instead of an array, allows us to extend it later on without fundamentally changing the format. I'm on board with your initial proposal as it's easy to do the work on the server side and make the API consumers life easier. 

One thing I stumbled over is that sizes should be array? `"sizes": ["16x16", "32x32", "96x96" ,"128x128", "256x256"]`?

For the definition inside the package. If we have also sizes for svg's, it means like for the screenshots, the icons plus meta data must be specified in the manifest file.

**Comment by jfsiii** [comment]
> One thing I stumbled over is that sizes should be array? `"sizes": ["16x16", "32x32", "96x96" ,"128x128", "256x256"]`

Yes. I think so. It's a list of values. We're using the Web App Manifest for inspiration, not trying to be compatible, so I think an array makes sense.

We're also free to use other values. e.g. only `16`, `256` since they're square or creating an enum like `s`, `m`, `l`). But I think `WxH` is preferable since it's explicit and flexible.

**Comment by ruflin** [comment]
Will open a PR with the suggested data in the packages API endpoint. If the creator of the integration needs to generate it manually or it's auto generated based on a convention can still be decided later.

**Comment by ruflin** [comment]
BTW I think this will also change the API in the way that if a package does not have an icon, not icon will be available, also not a default one. At the moment if a package does not have an icon, the default is exposed. But TBH I think it's better to let the UI decide if it wants to have a default icon or not.
