### ISSUE TITLE
Scaling the integrations registry service

### ISSUE THREAD

**Issue by ruflin** [elastic/integrations-registry#53]
Long term the availability of the integrations registry service becomes critical for each Kibana installation. This raises the question on how to make sure the registry is always available and easy to scale.

Large parts of the existing API endpoints are static. Data for an existing package never changes and all the package related API endpoints never change. This makes it possible instead of running a service which creates the responses on demand the pregenerate all the content and serve it from static files.

The `/list` endpoint is an exception to the above. This endpoints allows to query the existing packages based on different factors like versions of the components in the stack, existing plugins or even search queries in the future. This leads to millions or billions of different possible combinations. 

# Proposal

The proposal is to pregenerate all the content for the packages and package API endpoints. For the `/list` endpoint an actual service needs to be running that serves the on demand content.

**Comment by roncohen** [comment]
As you indicate, for the all endpoints that are essentially static, i don't think there's much to discuss when it comes to scalability. For the `/list` (soon `/search` https://github.com/elastic/integrations-registry/pull/57) endpoint, i think it's a good question how it will work and how the registry will be deployed/hosted.

It's important to provide high quality search. Letting users optionally use Elasticsearch to back the registry would be interesting.

**Comment by roncohen** [comment]
To address your concrete proposal, I'm not sure we need to generate static content right now. 

Asking people to run a simple go service doesn't seem like a problem, but i could be missing something.

**Comment by ruflin** [comment]
I started to play around with static content for some parts and it actually simplifies the code: https://github.com/elastic/integrations-registry/pull/58 For now it's still a go service that serves the static and the `/search` endpoint. This keeps us all options open.

The more I think about the search endpoint, the more I'm thinking ES as a search backend will even be required as it will make the service itself simpler and more efficient. Each ES instance would be independent and the service would load all the needed that into ES on startup.

As the registry service is completely independent it should be pretty simple to horizontally scale it. The part I don't know how much traffic we will expect as all newer Kibana instances will hit it pretty often.

**Comment by roncohen** [comment]
> The more I think about the search endpoint, the more I'm thinking ES as a search backend will even be required as it will make the service itself simpler and more efficient. Each ES instance would be independent and the service would load all the needed that into ES on startup.

The only problem is see with this is situations where users do not want their Kibana to reach outside their network and use our hosted registry. With ES required, it becomes slightly more complicated to run it, maintain it etc.

**Comment by ruflin** [comment]
My thinking here was that Elasticsearch would run directly inside the container itself as search backend. But that assumes they run it as docker container. It definitively makes sense more complicated if someone wants to run the go service directly. Need to think more about it.

**Comment by ruflin** [comment]
The current state here is that all endpoints are now pregenerated statically served files except `/search` and `/categories` endpoint. There is still a Golang http service running which serves the static files and the two additional endpoints. This should make scaling pretty easy even without hosting the static files in S3 / Google Cloud Storage.

All requests can heavily be cached by a CDN and only `/search` and `/categories` endpoint need to be invalidated on deploying a new version of the service. I expect the CDN to also cache results like `/search?kibana=7.3.1` or more complex queries. 

The advantage with the current behaviour is that we still just run a Docker container and everything just works, be it locally or in a Kubernetes cluster.

**Comment by ruflin** [comment]
The current plan is to run the registry itself inside k8s cluster and have a CDN in front. This should work well. Closing this for now until we hit some limits.
