### ISSUE TITLE
Proper content-type for SVGs

### ISSUE THREAD

**Issue by jfsiii** [elastic/integrations-registry#74]
The registry is serving SVG assets (icons) assets as `text/plain` but they should be served with `image/svg+xml`

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#Image_types

Compare
SVG (`text/plain`)
<img src="http://integrations-registry.app.elstc.co/package/coredns-1.0.1/img/icon.svg" />

PNG (`image/png`)
<img src="http://integrations-registry.app.elstc.co/package/coredns-1.0.1/img/icon.png"/>

I also noticed that the `/search` response includes `"type": "image/svg"`. This, too, should be `image/svg+xml` and seems like the registry should be sure to serve the assets using the `content-type` header as the `type` value.

**Comment by ruflin** [comment]
https://github.com/elastic/integrations-registry/pull/77 should solve the .svg issue. So far the header type is defined on the file ending and the default is json. Reason is that this content is now statically generated, so header decisions need to be made on paths.

Here you see the headers definitions, let me know if you would like some more headers to be added: https://github.com/elastic/integrations-registry/blob/master/handler.go#L169

I could not follow the part on the  `/search` endpoint, it seems to serve the json header?

**Comment by jfsiii** [comment]
> I could not follow the part on the /search endpoint, it seems to serve the json header?

I was referring to the JSON body. The `icons` section looks like

```
      {
        "src": "/package/coredns-1.0.1/img/icon.svg",
        "size": "255x144",
        "type": "image/svg"
      }
```

`"type": "image/svg"` should be `"type": "image/svg+xml"`

Also, it seems like the registry's value for serving `content-type` header and the value for `type` should be. It shouldn't be possible for them to be out of sync.

**Comment by ruflin** [comment]
Got it. The `type` which is served in the search list is directly coming from the package itself, so this needs updating. The content type served for the header is served based on the file (for now). They should be in sync but at the moment with the static file generation / serving, I don't have a place to store headers during generation. AFAIK this is possible with some cloud providers. As soon as we serve it from there, we can "sync up" the two.

Are you currently using the `type` inside the response or could I just skip it for now?

**Comment by jfsiii** [comment]
The Manager is avoiding the `icons` portion of response entirely at the moment, but when it does process them it will use the `type` and it should be `image/svg+xml`.

i.e. if you're OK with how things work now, and I am, this can wait until you get around to it.

**Comment by ruflin** [comment]
I will update the package definitions for now so when you use it, you get the correct `type` definition.

**Comment by ruflin** [comment]
Fixing this with https://github.com/elastic/integrations-registry/pull/83
