### ISSUE TITLE
Category names and counts

### ISSUE THREAD

**Issue by jfsiii** [elastic/integrations-registry#75]
The Manager UI has a section like

<img width="272" alt="Screen Shot 2019-08-28 at 1 36 30 PM" src="https://user-images.githubusercontent.com/57655/63879052-da86f380-c998-11e9-9b5b-4d931a9986a2.png">

which lists the available categories and the number of packages in each. 

The registry needs to supply the category names and counts 

For now something as simple as this would work

```
{
  "Logging": 12,
  "Metrics" 34,
  ...
  "Sample Data": 56
}
```

However, thinking forward a bit, I think this might be more like it

```
[
  {
    "id": "logging",
    "title": "Logging",
    "packages": ["package-a-1.2.3", "package-z-3.4.5"]
  },
  ...
  {
    "id": "sample-data",
    "title": "Sample Data",
    "packages": ["package-a-1.2.3", "package-z-3.4.5"]
  }
]
```

The idea is that we'll want `id` to use for `/search?category=${id}` or other endpoints and we can use `title` (or `label`, etc) to control the stylized text we show in the UI. 

`packages` could be replaced by something like `count`, but including the package ids (went with latest version only) makes client-side filtering easier.

**Comment by ruflin** [comment]
If you type a "search" filter on the Kibana UI, do you expect this list to change in real time? My suggestion for now would be that it keeps the total result. This basically means, the above output can be statically generated for now with all the existing packages.

To further simplify things on the registry end, I would suggest for now the result will be "mostly" accurate. What I mean by that is that it's a statically generated output with the all the most recent packages. If there is a package that was in the past only `logs` and the newest one is `logs` and `metrics`, it would show the stats for the newest package. Someone connecting with an older KB version would have a slightly inaccurate result.

I'm thinking of adding Elasticsearch as a backend to the registry mid / long term which would make all the above queries really simple.

**Comment by jfsiii** [comment]
> If you type a "search" filter on the Kibana UI, do you expect this list to change in real time? 

That's as much a question for you and Design as me, but no, I don't. I think they're static counts of what is available not what's on the screen. 

If we have enough intergrations that we're paginating the results, I think the counts in the sidebar stay the same as you go through the results; not update to reflect what's in that slice. Even if we did go that route, I think that'd all be handled client-side and the API needn't worry about it.

**Comment by ruflin** [comment]
Ok, for now keeping the logic simple but made a dynamic handler so I can play around with the ideas.

Off topic: Do you expect pagination to happen on the client side (I hope yes) :-)
